# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Martin's
tagline:          'staff'
description:      'You check my <a href="https://www.linkedin.com/in/martin-schaefer-251a8741" target="_blank">LinkedIn</a>, read about our research <a href="sum.fel.cvut.cz">projects</a> or just follow me <a href="https://twitter.com/schaefer_cz" target="_blank">@scahefer_cz</a>.'
url:              https://schaemar.github.io/hyde/
baseurl:          https://schaemar.github.io/hyde/

author:
  name:           'Martin Schaefer'
  url:            http://schaefer.cz

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/schaemar/www_blog
